---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ci-runner-worker.labels" . | nindent 4 }}
data:
  WORKER_VERSION: {{ .Values.repository.tag | quote }}
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
