{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ci-runner-worker.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ci-runner-worker.labels" . | nindent 4 }}
  {{- with .Values.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsService.servicePort }}
      targetPort: {{ .Values.metricsService.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "ci-runner-worker.selectorLabels" . | nindent 4 }}
{{- end }}
