{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.customName | default (include "ci-runner-worker.fullname" .) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ci-runner-worker.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ci-runner-worker.selectorLabels" . | nindent 4 }}
{{- end }}
